version: '3.8'

services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "uv run uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
